App_login/urls.py
from django.urls import path
from App_login.views import *

app_name = "App_login"

urlpatterns = [
    path('', home, name='home'),
    path('register/', register_attempt, name="register_attempt"),
    path('login/', login_attempt, name="login_attempt"),
    path('token/', token_send, name="token_send"),
    path('success/', success, name='success'),
    path('verify/<auth_token>', verify, name="verify"),
    path('error/', error_page, name="error")
]

OurEcom/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

App_login/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from datetime import date

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy
from django_countries.fields import CountryField
from image_optimizer.fields import OptimizedImageField
from phonenumber_field.modelfields import PhoneNumberField


class MyUserManager(BaseUserManager):
    """ A custom Manager to deal with emails as unique identifer """

    def _create_user(self, email, password, **extra_fields):
        """ Creates and saves a user with a given email and password"""

        if not email:
            raise ValueError("The Email must be set!")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=False)
    is_staff = models.BooleanField(
        ugettext_lazy('staff status'),
        default=False,
        help_text=ugettext_lazy('Designates whether the user can log in this site')
    )

    is_active = models.BooleanField(
        ugettext_lazy('active'),
        default=True,
        help_text=ugettext_lazy(
            'Designates whether this user should be treated as active. Unselect this instead of deleting accounts')
    )

    USERNAME_FIELD = 'email'
    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='profile')
    username = models.CharField(max_length=264, blank=True, null=True)
    full_name = models.CharField(max_length=264, blank=True, null=True)
    phone_number = PhoneNumberField(unique=True, blank=True, null=True)
    country = CountryField(blank_label='(select country)', null=True)
    House = models.TextField(max_length=300, blank=True, null=True)
    city = models.CharField(max_length=40, blank=True, null=True)
    zipcode = models.CharField(max_length=10, blank=True, null=True)
    profile_picture = OptimizedImageField(blank=True, null=True)
    auth_token = models.CharField(max_length=100)
    is_verified = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True, null=True)

    def is_fully_filled(self):
        fields_names = [f.name for f in self._meta.get_fields()]

        for field_name in fields_names:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False
        return True

App_login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from App_login.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)

App_login/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from App_login.models import Profile, User
from django.shortcuts import redirect, render
from django.contrib import messages

from .forms import SignUpForm
from .models import *
import uuid
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required


# Create your views here.
def home(request):
    return render(request, "App_login/home.html")


def login_attempt(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            profile_obj = Profile.objects.get(user=user, is_verified=True)

            if profile_obj:
                if user is not None:
                    login(request, user)
                    return HttpResponseRedirect(reverse('App_login:home'))
                else:
                    messages.success(request, 'Wrong password.')
                    return HttpResponseRedirect(reverse('App_login:login_attempt'))
            else:
                messages.success(request, 'Profile is not verified check your mail.')
                return HttpResponseRedirect(reverse('App_login:login_attempt'))

        return HttpResponseRedirect(reverse('App_login:home'))
    content = {
        'form': form
    }
    return render(request, 'App_login/login.html', context=content)


def register_attempt(request):
    form = SignUpForm()
    if request.method == 'POST':
        email = request.POST.get('email')
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            user_id = User.objects.get(email=email)
            try:
                auth_token = str(uuid.uuid4())
                profile_obj = Profile.objects.create(user=user_id, auth_token=auth_token)
                profile_obj.save()
                send_mail_after_registration(email, auth_token)
                return HttpResponseRedirect(reverse('App_login:token_send'))
            except Exception as e:
                print(e)

    content = {
        'form': form
    }
    return render(request, 'App_login/register.html', context=content)


def success(request):
    return render(request, 'App_login/success.html')


def token_send(request):
    return render(request, 'App_login/token_send.html')


def verify(request, auth_token):
    try:
        profile_obj = Profile.objects.filter(auth_token=auth_token).first()

        if profile_obj:
            if profile_obj.is_verified:
                messages.success(request, 'Your account is already verified.')
                return HttpResponseRedirect(reverse('App_login:login_attempt'))
            profile_obj.is_verified = True
            profile_obj.save()
            messages.success(request, 'Your account has been verified.')
            return HttpResponseRedirect(reverse('App_login:login_attempt'))
        else:
            return HttpResponseRedirect(reverse('App_login:success'))
    except Exception as e:
        print(e)
        return HttpResponseRedirect(reverse('App_login:home'))


def error_page(request):
    return render(request, 'App_login/error.html')


def send_mail_after_registration(email, token):
    subject = 'Your accounts need to be verified'
    message = f'Hi paste the link to verify your account http://127.0.0.1:8000/accounts/verify/{token}'
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [email]
    send_mail(subject, message, email_from, recipient_list)

templates/App_login/AuthBase.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Django!</title>

    <style>
        html, body {
            height: 100%;
        }

        .global-container {
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: #f5f5f5;
        }

        form {
            padding-top: 10px;
            font-size: 14px;
            margin-top: 30px;
        }

        .card-title {
            font-weight: 300;
        }

        .btn {
            font-size: 14px;
            margin-top: 20px;
        }


        .login-form {
            width: 330px;
            margin: 20px;
        }

        .sign-up {
            text-align: center;
            padding: 20px 0 0;
        }

        .alert {
            margin-bottom: -30px;
            font-size: 13px;
            margin-top: 20px;
        }
    </style>
</head>
<body>

{% block content %}
{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

templates/App_login/error.html
{% extends 'App_login/AuthBase.html' %}
{% block content %}
    <div class="global-container">
        <div class="card login-form">
            <div class="card-body">
                <h3 class="card-title text-center">Error</h3>

                <a href="/" class="btn btn-success">Back</a>

            </div>
        </div>
    </div>
{% endblock %}

templates/App_login/home.html
{% extends 'App_login/AuthBase.html' %}
{% block content %}
    <h1>Home</h1>
{% endblock %}

templates/App_login/login.html
{% extends "App_login/AuthBase.html" %}
{% load crispy_forms_filters %}
{% block content %}
    <div class="global-container">
        <div class="card login-form">
            <div class="card-body">
                <h3 class="card-title text-center">Log in to Django</h3>
                {% if messages %}

                    {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                    {% endfor %}

                {% endif %}
                <div class="card-text">
                    <!--
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">Incorrect username or password.</div> -->
                    <form method="post">
                        {% csrf_token %}
                        <!-- to error: add class "has-danger" -->
                        <div class="form-group">
                            {{ form|crispy }}
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Sign in</button>

                        <div class="sign-up">
                            Don't have an account? <a href="{% url 'App_login:register_attempt' %}">Create One</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        let email = document.getElementById("id_username");
        let pass1 = document.getElementById("id_password");

        email.classList.add('form-control');
        pass1.classList.add('form-control');
    </script>

{% endblock %}

templates/App_login/register.html
{% extends "App_login/AuthBase.html" %}
{% load crispy_forms_filters %}
{% block content %}

    <div class="global-container">
        <div class="card login-form">
            <div class="card-body">
                <h3 class="card-title text-center">Register in to Django</h3>
                <div class="card-text">
                    {% if messages %}

                        {% for message in messages %}
                            <div class="alert alert-info">
                                {{ message }}
                            </div>
                        {% endfor %}

                    {% endif %}
                    <!--
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">Incorrect username or password.</div> -->
                    <form method="post">
                        {% csrf_token %}

                        <div class="form-group">
                            {{ form|crispy }}
                        </div>
                        <a href="#" style="float:right;font-size:12px;">Forgot password?</a>

                        <button type="submit" class="btn btn-primary btn-block mt-2">Sign in</button>

                        <div class="sign-up mt-2">
                            Already have an account? <a href="{% url 'App_login:login_attempt' %}">Create One</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        let email = document.getElementById("id_email");
        let pass1 = document.getElementById("id_password1");
        let pass2 = document.getElementById("id_password2");

        email.classList.add('form-control');
        pass1.classList.add('form-control');
        pass2.classList.add('form-control');
    </script>

{% endblock %}

templates/App_login/success.html
{% extends "App_login/AuthBase.html" %}

{% block content %}
    <div class="global-container">
        <div class="card login-form">
            <div class="card-body">
                <h3 class="card-title text-center">Hurray your mail is verified </h3>
                <div class="card-text text-center">
                    Please login
                </div>
                <div class="text-center">
                    <a class="btn btn-primary" href="{% url 'App_login:login_attempt' %}">Login</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/App_login/token_send.html
{% extends "App_login/AuthBase.html" %}

{% block content %}
    <div class="global-container">
        <div class="card login-form">
            <div class="card-body">
                <h3 class="card-title text-center">We have sent an email to you </h3>
                <div class="card-text text-center">
                    Please check your mail
                </div>
            </div>
        </div>
    </div>
{% endblock %}